Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.posts.views import index

urlpatterns = [
    path('', index),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('apps.posts.urls'))
]

apps/posts/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<tag_slug>', post_list, name='post_list_by_tag'),
    path('<str:slug>', post_detail, name='post_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import  RichTextUploadingField
from taggit.managers import TaggableManager

"""
from apps.posts.models import Post
posts = Post.objects.all()
publicados = Post.publicados.all()
"""


class PostPublished(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(estado='publicado').order_by('-created')


def user_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.slug, filename)


class Post(models.Model):
    ESTADO_POST = (
        ('borrador', 'Borrador'),
        ('publicado', 'Publicado'),
    )
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, )
    # contenido = models.TextField()
    # contenido = RichTextField()
    contenido = RichTextUploadingField()
    publish = models.DateField(default=timezone.localtime)
    created = models.DateField(auto_now_add=True, verbose_name='creado')
    updated = models.DateField(auto_now=True)
    estado = models.CharField(max_length=10, choices=ESTADO_POST, default='borrador')
    image = models.ImageField(upload_to=user_directory_path, blank=True, )

    objects = models.Manager()  # The default manager.
    publicados = PostPublished()  # The PostPublished manager.
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:post_detail', args=[str(self.slug)])


class Comentario(models.Model):
    post = models.ForeignKey(Post, related_name='comentarios', on_delete=models.CASCADE, )
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    contenido = models.TextField()
    created = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comentario por {}'.format(self.nombre)

apps/posts/views.py
from django.shortcuts import render, get_object_or_404
from taggit.models import Tag

from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def index(request):
    response = render(request, 'index.html')

    if not request.COOKIES.get('visits'):
        response.set_cookie('visits', '1', 3600)
    else:
        visits = int(request.COOKIES.get('visits', '1')) + 1
        response.set_cookie('visits', str(visits), 3600)

    return response


def post_list(request, tag_slug=None):
    object_list = Post.publicados.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 5)  # Show n posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.get_page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    return render(request, 'blog/posts_list.html', {'posts': posts, 'titulo': 'Listado', 'tag': tag})


def post_detail(request, slug):
    post = get_object_or_404(Post, estado='publicado', slug=slug)
    context = {'post': post, 'titulo': "Detalle"}
    return render(request, 'blog/post_detail.html', context)

apps/posts/templates/base/interior.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{ titulo }} {% endblock %}</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="utf-8">
    <meta name="author" content="Roman Kirichik">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/apple-touch-icon-114x114.png' %}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-responsive.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/animations.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/vertical-rhythm.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/colors/blue.css' %}">

</head>
<body class="appear-animate">

<!-- Page Loader -->
<div class="page-loader">
    <b class="spinner">Loading...</b>
</div>
<!-- End Page Loader -->

<!-- Page Wrap -->
<div class="page" id="top">


    <!-- Navigation panel -->
    <nav class="main-nav dark stick-fixed">
        <div class="container relative clearfix">

            <!-- Logo ( * your text or image into link tag *) -->
            <div class="nav-logo-wrap local-scroll">
                <a href="#top" class="logo"><img src="{% static 'images/logo-white.png' %}" width="80" height="27"
                                                 alt=""/></a>
            </div>

            <div class="mobile-nav"><i class="fa fa-bars"></i></div>

            <!-- Main Menu -->
            <div class="inner-nav desktop-nav">
                 {% include 'blog/bloques/header.html' %}
            </div>

        </div>
    </nav>
    <!-- End Navigation panel -->


    <!-- Home Section -->
    <section class="page-section bg-dark-alfa-90"
             data-background="{% static 'images/full-width-images/section-bg-9.jpg ' %}">
        <div class="container relative pt-40">

            <div class="align-center">

                <div class="big-icon">
                    <i class="fa fa-pencil"></i>
                </div>

                <h3 class="small-title white">

                    <span class="serif">The great</span>
                    creative minds
                    <span class="serif">in our blog</span>
                    <br class="hidden-xs"/>are here
                    <span class="serif"> to make your </span>
                    big ideas
                    <span class="serif"> possible</span>

                </h3>

            </div>

        </div>
    </section>
    <!-- End Home Section -->


    <!-- Content Section -->
    <section class="page-section">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}
                {% include 'blog/bloques/sidebar.html' %}
            </div>

        </div>
    </section>
    <!-- End Content Section -->


    <!-- Foter -->
    <footer class="small-section bg-dark footer">
        <div class="container">

            <!-- Footer Text -->
            <div class="footer-text">

                <!-- Copyright -->
                <div class="footer-copy">
                    <a href="http://themeforest.net/user/theme-guru/portfolio" target="_blank">&copy; BigStream <span
                            class="number">2014</span></a>.
                </div>
                <!-- End Copyright -->

                <div class="footer-made">
                    Made with <span class="serif">love</span>
                    for <span class="serif">great people</span>.
                </div>

            </div>
            <!-- End Footer Text -->

            <!-- Social Links -->
            <div class="footer-social-links">
                <div class="social-links tooltip-bot">
                    <a href="#" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="#" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="#" title="Google+" target="_blank"><i class="fa fa-google-plus"></i></a>
                    <a href="#" title="LinkedIn+" target="_blank"><i class="fa fa-linkedin"></i></a>
                    <a href="#" title="Pinterest" target="_blank"><i class="fa fa-pinterest"></i></a>
                    <a href="#" title="E-mail" target="_blank"><i class="fa fa-envelope"></i></a>
                </div>
            </div>
            <!-- End Social Links -->

        </div>
    </footer>
    <!-- End Foter -->


</div>
<!-- End Page Wrap -->


<!-- JS -->
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.localScroll.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ba-hashchange.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.viewport.mini.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.appear.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.sticky.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.fitvids.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/all.js' %}"></script>
<script type="text/javascript" src="{% static 'js/contact-form.js' %}"></script>
<script type="text/javascript" src="{% static 'js/animations.min.js' %}"></script>
<!--[if lt IE 10]><script type="text/javascript" src="js/placeholder.js"></script><![endif]-->

</body>
</html>

apps/posts/templates/blog/bloques/header.html
<ul class="clearlist scroll-nav local-scroll">
    <li><a href="/">Home</a></li>
    <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
</ul>

apps/posts/templates/blog/bloques/paginacion.html
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page.has_previous %}#}
{#            <a href="?page=1">&laquo; primera</a>#}
{#            <a href="?page={{ page.previous_page_number }}">anterior</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Pagina {{ page.number }} of {{ page.paginator.num_pages }}#}
{#        </span>#}
{##}
{#        {% if page.has_next %}#}
{#            <a href="?page={{ page.next_page_number }}">siguiente</a>#}
{#            <a href="?page={{ page.paginator.num_pages }}">ultima &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}


<!-- Pagination -->
<div class="pagination">


    {% if page.has_previous %}
        <a href="?page=1">Primero</a>
        <a href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a>
        {#        {% if (page.paginator.num_pages - 3) > 1) %}#}
        {#            <a href="?page={{ page.previous_page_number }}">Anterior</a>#}
        {#        {% endif %}#}
    {% endif %}
    {% if page.number > 1 %}
        <a class="active">{{ page.number }} </a>
    {% endif %}
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
        {#        <a href="?page={{ page.paginator.num_pages }}">ultima &raquo;</a>#}
        <a href="?page={{ page.paginator.num_pages }}">Último</a>
    {% endif %}
    {#    <a class="no-active">...</a>#}

</div>
<!-- End Pagination -->

apps/posts/templates/blog/bloques/sidebar.html
<!-- Sidebar -->
<div class="col-sm-3 col-sm-offset-1 sidebar">

    <!-- Search Widget -->
    <div class="widget">
        <form class="form-inline form" role="form">
            <div class="search-wrap">
                <button class="search-button animate" type="submit" title="Start Search">
                    <span class="icon-magnifier"></span>
                </button>
                <input type="text" class="form-control search-field" placeholder="Search...">
            </div>
        </form>
    </div>
    <!-- End Search Widget -->

    <!-- Widget -->
    <div class="widget">

        <h5 class="widget-title">Categories</h5>

        <div class="widget-body">
            <ul class="clearlist widget-menu">
                <li>
                    <a href="#" title="">Branding</a>
                    <small>
                        - 7
                    </small>
                </li>
                <li>
                    <a href="#" title="">Design</a>
                    <small>
                        - 15
                    </small>
                </li>
                <li>
                    <a href="#" title="">Development</a>
                    <small>
                        - 3
                    </small>
                </li>
                <li>
                    <a href="#" title="">Photography</a>
                    <small>
                        - 5
                    </small>
                </li>
                <li>
                    <a href="#" title="">Other</a>
                    <small>
                        - 1
                    </small>
                </li>
            </ul>
        </div>

    </div>
    <!-- End Widget -->

    <!-- Widget -->
    <div class="widget">

        <h5 class="widget-title">Tags</h5>

        <div class="widget-body">
            <div class="tags">
                <a href="">Design</a>
                <a href="">Portfolio</a>
                <a href="">Digital</a>
                <a href="">Branding</a>
                <a href="">Theme</a>
                <a href="">Clean</a>
                <a href="">UI & UX</a>
                <a href="">Love</a>
            </div>
        </div>

    </div>
    <!-- End Widget -->



    <!-- Widget -->
    <div class="widget">

        <h5 class="widget-title">Last posts</h5>

        <div class="widget-body">
            <ul class="clearlist widget-posts">
                <li>
                    Posted by John Doe 7 Mar <a href="#" title="">Lorem ipsum dolor sit amet</a>
                </li>
                <li>
                    Posted By Emma Johnson 7 Mar <a href="#" title="">Suspendisse accumsan interdum
                    tellus</a>
                </li>
                <li>
                    Posted by John Doe 7 Mar <a href="#" title="">Praesent ultricies ut ipsum</a>
                </li>
                <li>
                    Posted Mark Deen 5 Mar <a href="#" title="">Vivamus malesuada vel nulla
                    vulputate</a>
                </li>
                <li>
                    Posted by Sam Brin 3 Mar <a href="#" title="">Aenean auctor egestas auctor</a>
                </li>
            </ul>
        </div>

    </div>
    <!-- End Widget -->

</div>
<!-- End Sidebar -->

apps/posts/templates/blog/post_detail.html
{% extends 'base/interior.html' %}
{% load staticfiles %}
{% block content %}
    <!-- Content -->
    <div class="col-sm-7 col-sm-offset-1">

        <!-- Post -->
        <div class="blog-item mb-80 mb-xs-40">
            <!-- Media Gallery -->
            <div class="blog-media mt-40 mb-40 mb-xs-30">
                {% if post.image %}
                    <img src="{% static 'media/' %}{{ post.image }}" alt=""/>
                {% else %}
                    <img src="{% static 'images/portfolio/full-project-4.jpg' %}" alt=""/>
                {% endif %}
            </div>

            <h1 class="mt-0">{{ post.titulo }}</h1>

            <!-- Text -->
            <div class="blog-item-body">

                <p>
                    {{ post.contenido|safe }}
                </p>
            </div>
            <!-- End Text -->

        </div>
        <!-- End Post -->

        <!-- Comments -->
        <div class="mb-80 mb-xs-40">

            <h6 class="blog-page-title uppercase">Comments
                ({{ post.comentarios.count }})
            </h6>

            <ul class="media-list text comment-list">

                <!-- Comment Item -->
                <li class="media comment-item">

                    <a class="pull-left" href="#">

                        <img class="media-object comment-avatar"
                             src="{% static 'images/user-avatar.png ' %}" alt="" width="50"
                             height="50"></a>

                    <div class="media-body">

                        <div class="comment-item-data">
                            <div class="comment-author">
                                <a href="#">John Doe</a>
                            </div>
                            Feb 9, 2014, at 10:23<span class="separator">&mdash;</span>
                            <a href="#"><i class="fa fa-comment"></i>&nbsp;Reply</a>
                        </div>

                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at magna ut ante
                            eleifend eleifend.
                        </p>

                        <!-- Comment of second level -->
                        <div class="media comment-item">

                            <a class="pull-left" href="#"><img class="media-object comment-avatar"
                                                               src="{% static 'images/user-avatar.png' %}" alt=""></a>

                            <div class="media-body">

                                <div class="comment-item-data">
                                    <div class="comment-author">
                                        <a href="#">Sam Brin</a>
                                    </div>
                                    Feb 9, 2014, at 10:27<span class="separator">&mdash;</span>
                                    <a href="#"><i class="fa fa-comment"></i>&nbsp;Reply</a>
                                </div>

                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at magna ut
                                    ante eleifend eleifend.
                                </p>


                            </div>

                        </div>
                        <!-- End Comment of second level -->

                    </div>

                </li>
                <!-- End Comment Item -->

                <!-- Comment Item -->
                <li class="media comment-item">

                    <a class="pull-left" href="#"><img class="media-object comment-avatar"
                                                       src="{% static 'images/user-avatar.png' %}" alt=""></a>

                    <div class="media-body">

                        <div class="comment-item-data">
                            <div class="comment-author">
                                <a href="#">Emma Johnson</a>
                            </div>
                            Feb 9, 2014, at 10:37<span class="separator">&mdash;</span>
                            <a href="#"><i class="fa fa-comment"></i>&nbsp;Reply</a>
                        </div>

                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at magna ut ante
                            eleifend eleifend.
                        </p>

                    </div>

                </li>
                <!-- End Comment Item -->

                <!-- Comment Item -->
                <li class="media comment-item">

                    <a class="pull-left" href="#"><img class="media-object comment-avatar"
                                                       src="{% static 'images/user-avatar.png' %}" alt=""></a>

                    <div class="media-body">

                        <div class="comment-item-data">
                            <div class="comment-author">
                                <a href="#">John Doe</a>
                            </div>
                            Feb 9, 2014, at 10:3<span class="separator">&mdash;</span>
                            <a href="#"><i class="fa fa-comment"></i>&nbsp;Reply</a>
                        </div>

                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at magna ut ante
                            eleifend eleifend.
                        </p>

                    </div>

                </li>
                <!-- End Comment Item -->

            </ul>

        </div>
        <!-- End Comments -->


        <!-- Add Comment -->
        <div class="mb-80 mb-xs-40">

            <h6 class="blog-page-title uppercase">Leave a comment</h6>

            <!-- Form -->
            <form method="post" action="#" id="form" role="form" class="form">

                <div class="row mb-20 mb-md-10">

                    <div class="col-md-6 mb-md-10">
                        <!-- Name -->
                        <input type="text" name="name" id="name" class="form-control" placeholder="Name *"
                               maxlength="100" required>
                    </div>

                    <div class="col-md-6">
                        <!-- Email -->
                        <input type="email" name="email" id="email" class="form-control" placeholder="Email *"
                               maxlength="100" required>
                    </div>

                </div>

                <div class="mb-20 mb-md-10">
                    <!-- Website -->
                    <input type="text" name="website" id="website" class="form-control" placeholder="Website"
                           maxlength="100" required>
                </div>

                <!-- Comment -->
                <div class="mb-30 mb-md-10">
                        <textarea name="text" id="text" class="form-control" rows="6" placeholder="Comment"
                                  maxlength="400"></textarea>
                </div>

                <!-- Send Button -->
                <button type="submit" class="btn btn-mod btn-medium">
                    Send comment
                </button>

            </form>
            <!-- End Form -->

        </div>
        <!-- End Add Comment -->

        <!-- Prev/Next Post -->
        <div class="clearfix mt-40">
            <a href="#" class="blog-item-more left"><i class="fa fa-angle-left"></i>&nbsp;Prev post</a>
            <a href="#" class="blog-item-more right">Next post&nbsp;<i class="fa fa-angle-right"></i></a>
        </div>
        <!-- End Prev/Next Post -->


    </div>
    <!-- End Content -->
{% endblock %}

apps/posts/templates/blog/posts_list.html
{% extends 'base/interior.html' %}
{% load staticfiles %}
{% block content %}
    <!-- Content -->
    <div class="col-sm-7 col-sm-offset-1">
    {% if tag %}
       <h2>Pots de la categoria "{{ tag.name }}"</h2>
    {% endif %}
        {% for post in posts %}
            <!-- Post -->
            <div class="blog-item">

                <!-- Date -->
                <div class="blog-item-date">
                    <span class="date-num">{{ post.publish.day }}</span> {{ post.publish|date:"b" }}
                </div>
                <!-- Post Title -->
                <h2 class="blog-item-title animate"><a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a></h2>

                <!-- Author, Categories, Comments -->
                <div class="blog-item-data">
                    Posted by <a href="#">{{ post.autor.first_name }} {{ post.autor.last_name }}</a>
                    <span class="separator">&mdash;</span>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    <span class="separator">&mdash;</span>
                    <a href="#">{{ post.comentarios.count }}&nbsp;Comments</a>
                </div>

                <!-- Image -->
                {% if post.image %}
                    <div class="blog-media">
                        <a href="{{ post.get_absolute_url }}"><img
                                src="{% static 'media/' %}{{ post.image }}"
                                alt=""/></a>
                    </div>
                {% else %}
                    <div class="blog-media">
                        <a href="blog-post.html"><img
                                src="{% static 'images/portfolio/full-project-4.jpg' %}"
                                alt=""/></a>
                    </div>
                {% endif %}

                <!-- Text Intro -->
                <div class="blog-item-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at magna ut ante
                        eleifend eleifend. Aliquam ac libero et diam rutrum rutrum. Nullam interdum mattis
                        ipsum at convallis.
                    </p>
                </div>

                <!-- Read More Link -->
                <div class="blog-item-foot">
                    <a href="blog-post.html" class="btn btn-mod  btn-small">Read More <i
                            class="fa fa-angle-right"></i></a>
                </div>

            </div>
        {% empty %}
            <h1>No hay posts</h1>
        {% endfor %}


        {% include 'blog/bloques/paginacion.html' with page=posts %}


    </div>
    <!-- End Content -->
{% endblock %}